name: deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
        
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: install dependencies
        run: go mod download

      - name: build app
        run: go build -o main

      # - name: login to AWS ECR
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t my-registry/my-repo:latest .
      #     docker push my-registry/my-repo:latest

      # - name: configure env   
              
      #   env:
      #     AWS_REGION: ${{ env.AWS_REGION }}
      #     CDK_DEPLOY_ACCOUNT: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     CDK_DEPLOY_REGION: ${{ env.AWS_REGION }}
      #     CDK_STACK_NAME: ${{ env.CDK_STACK_NAME }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: "us-east-1"

      
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Deploy CDK stack
        run: cdk deploy --require-approval never --app 'node bin/deploy.ts'
